#!/bin/bash

set -e
set -x

if [ "$(id -u)" -ne 0 ] ; then
    echo 'You must be root to run this script'
    exit 1
fi

/bin/nohup /bin/screen -dm bash -c '/home/david/workspace/media-library-homepage/deploy-media-library-homepage.sh'


