#! /bin/bash

### BEGIN INIT INFO
# Provides:          media-library-homepage-server
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: media-library-homepage-server service
# Description:       Run media-library-homepage-server service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting media-library-homepage-server..."
    /var/opt/media-library-homepage-server/start-media-library-homepage-server.sh
    ;;
  stop)
    echo "Stopping media-library-homepage-server..."
    /var/opt/media-library-homepage-server/stop-media-library-homepage-server.sh
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/media-library-homepage-server {start|stop}"
    exit 1
    ;;
esac

exit 0
